# Generated by Django 5.2.7 on 2025-10-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application2", "0004_passport_person_delete_employee_passport_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passport",
            name="date_issued",
        ),
    ]
