# Generated by Django 5.2.7 on 2025-10-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registercrudapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("empid", models.CharField(max_length=50)),
                ("salary", models.CharField(max_length=50)),
            ],
        ),
    ]
