# Generated by Django 5.2.7 on 2025-10-09 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Designation", models.CharField(max_length=50)),
                ("Salary", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ConfidentialInfo",
            fields=[
                ("emp_id", models.IntegerField()),
                (
                    "Name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="application2.employee",
                    ),
                ),
            ],
        ),
    ]
