# Generated by Django 5.2.7 on 2025-10-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application2", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="confidentialinfo",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="Designation",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="Salary",
            new_name="salary",
        ),
    ]
