# Generated by Django 5.2.7 on 2025-10-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application2", "0002_rename_name_confidentialinfo_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="Name",
            new_name="name",
        ),
        migrations.DeleteModel(
            name="ConfidentialInfo",
        ),
    ]
