# Generated by Django 5.2.7 on 2025-10-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application2", "0003_rename_name_employee_name_delete_confidentialinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passport_number", models.CharField(max_length=50)),
                ("date_issued", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.AddField(
            model_name="passport",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="application2.person"
            ),
        ),
    ]
