# Generated by Django 5.2.7 on 2025-10-09 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Capital",
            fields=[
                ("capital", models.CharField()),
                (
                    "country",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="application1.country",
                    ),
                ),
            ],
        ),
    ]
