# Generated by Django 5.2.7 on 2025-10-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                ("name", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("marks", models.FloatField()),
            ],
        ),
    ]
