# Generated by Django 5.2.7 on 2025-10-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application1", "0002_country_capital"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capital",
            name="capital",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="country",
            name="country",
            field=models.CharField(max_length=50),
        ),
    ]
