# Generated by Django 5.2.7 on 2025-10-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeetable",
            name="id",
        ),
        migrations.AlterField(
            model_name="employeetable",
            name="empid",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="employeetable",
            name="role",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="employeetable",
            name="salary",
            field=models.FloatField(),
        ),
    ]
