# Generated by Django 5.2.7 on 2025-10-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentTable",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("rollno", models.IntegerField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
            ],
        ),
    ]
