# Generated by Django 5.2.7 on 2025-10-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studenttable",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
