# Generated by Django 5.2.7 on 2025-10-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRegistration",
            fields=[
                ("name", models.CharField(max_length=20)),
                (
                    "username",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=10)),
            ],
        ),
    ]
